### ISSUE TITLE
大佬，可以给个联系方式吗，对于这个项目有些问题希望可以请教您

### ISSUE THREAD

**Issue by DeepSpace98** [tbcvContributor/DeepHawkeye#3]

**Comment by cvlzw** [comment]
> _No description provided._

lzw9612@gmail.com

**Comment by wangtianlei1998** [comment]
hi，I just wanna run the demo_test, but ,here are some problems.
 
RuntimeError: Error in faiss::(anonymous namespace)::FileIOReader::FileIOReader(const char *) at index_io.cpp:136: Error: 'f' failed: could not open ./index_lib/grid_populated.index for reading: No such file or directory

so could you please give me your  ./index_lib/grid_populated.index.

Thanks!
