### ISSUE TITLE
RuntimeError: Error in faiss::(anonymous namespace)::FileIOReader::FileIOReader(const char *) at index_io.cpp:136: Error: 'f' failed: could not open ./index_lib/grid_populated.index for reading: No such file or directory

### ISSUE THREAD

**Issue by wangtianlei1998** [tbcvContributor/DeepHawkeye#4]
hi，I just wanna run the demo_test, but ,here are some problems.

RuntimeError: Error in faiss::(anonymous namespace)::FileIOReader::FileIOReader(const char *) at index_io.cpp:136: Error: 'f' failed: could not open ./index_lib/grid_populated.index for reading: No such file or directory

so could you please give me your ./index_lib/grid_populated.index.

Thanks

**Comment by cvlzw** [comment]
python demo_train.py -d ./demo_data/grid/normal_data -c grid
